name: Go Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    # Install dependencies and initialize workspace
    - name: Initialize Go workspace
      run: |
        make init

    # Run tests for each module
    - name: Run tests
      run: |
        make test
